pipeline:

  test:
    image: node:10
    environment:
      TASKFLOW_POSTGRES_HOST: database
      TASKFLOW_POSTGRES_USER: taskflow-test
      TASKFLOW_POSTGRES_PASSWORD: test-password
    commands:
      - npm ci
      - npm test
    when:
      event: [push, pull_request, tag]

  audit:
    image: node:10
    commands:
      - npx @lennym/ciaudit
    when:
      event: [push, pull_request, tag]

  publish:
    image: plugins/npm
    secrets:
      - npm_token
      - npm_email
    token: ${NPM_TOKEN}
    email: ${NPM_EMAIL}
    when:
      event: tag

services:
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=test-password
      - POSTGRES_USER=taskflow-test
